#!/bin/sh
### BEGIN INIT INFO
# Provides:          app.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$1" in
start)
   /home/pi/brain-admin/venv/bin/python /home/pi/brain-admin/app.py &
   echo $!>/var/run/brain-manager.pid
   ;;
stop)
   kill `cat /var/run/brain-manager.pid`
   rm /var/run/brain-manager.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/brain-manager.pid ]; then
      echo brain-manager is running, pid=`cat /var/run/brain-manager.pid`
   else
      echo brain-manager is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
