#!/bin/sh
### BEGIN INIT INFO
# Provides:          app.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

[ -f /etc/default/brain-manager ] && . /etc/default/brain-manager

if [ -z "$VIRTUALSKIN_BRAIN_ADMIN" ] ;  then
  echo "VIRTUALSKIN_BRAIN_ADMIN is not set, please set it in /etc/default/brain-manager" >> /tmp/brain-manager.log
  exit 1
fi

case "$1" in
start)
#   $VIRTUALSKIN_BRAIN_ADMIN/venv/bin/gunicorn app:app --bind 0.0.0.0:8080 >> $VIRTUALSKIN_BRAIN_ADMIN/run.log
   $VIRTUALSKIN_BRAIN_ADMIN/venv/bin/python $VIRTUALSKIN_BRAIN_ADMIN/app.py >> $VIRTUALSKIN_BRAIN_ADMIN/run.log &
   echo $!>/var/run/brain-manager.pid
   ;;
stop)
   kill `cat /var/run/brain-manager.pid`
   rm /var/run/brain-manager.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/brain-manager.pid ]; then
      echo brain-manager is running, pid=`cat /var/run/brain-manager.pid`
   else
      echo brain-manager is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
   echo "$VIRTUALSKIN_BRAIN_ADMIN"
esac

exit 0
